const { ethers, artifacts } = require("hardhat");
const { existsSync, mkdirSync, writeFileSync } = require("fs");
const { join } = require("path");

async function main() {
  console.log("Deploying contracts to BSC Testnet...");

  // Get signers
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);

  // Get account balance
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "BNB");

  if (balance === 0n) {
    console.error("\n❌ Error: Account has no BNB. Get testnet BNB from https://testnet.bnbchain.org/faucet-smart");
    process.exit(1);
  }

  // Deploy AuctionFactory
  console.log("\nDeploying AuctionFactory...");
  const AuctionFactory = await ethers.getContractFactory("AuctionFactory");
  const factory = await AuctionFactory.deploy();
  await factory.waitForDeployment();

  const factoryAddress = await factory.getAddress();
  console.log("✓ AuctionFactory deployed to:", factoryAddress);

  // Create src directories if they don't exist
  const constantsDir = join(__dirname, "../src/constants");
  const utilsDir = join(__dirname, "../src/utils");

  if (!existsSync(constantsDir)) {
    mkdirSync(constantsDir, { recursive: true });
  }
  if (!existsSync(utilsDir)) {
    mkdirSync(utilsDir, { recursive: true });
  }

  // Save deployment config
  const configPath = join(constantsDir, "config.js");
  const configContent = `// Auto-generated by deployment script
// Do not edit manually

export const FACTORY_ADDRESS = "${factoryAddress}";

export const NETWORK_CONFIG = {
  chainId: "0x61", // 97 (BSC Testnet)
  chainName: "BSC Testnet",
  nativeCurrency: {
    name: "BNB",
    symbol: "tBNB",
    decimals: 18
  },
  rpcUrls: ["https://data-seed-prebsc-1-s1.binance.org:8545/"],
  blockExplorerUrls: ["https://testnet.bscscan.com/"]
};
`;

  writeFileSync(configPath, configContent);
  console.log("✓ Config saved to:", configPath);

  // Save ABI files
  const factoryArtifact = await artifacts.readArtifact("AuctionFactory");
  const auctionArtifact = await artifacts.readArtifact("Auction");

  const abiPath = join(utilsDir, "abis.js");
  const abiContent = `// Auto-generated ABIs
// Do not edit manually

export const FACTORY_ABI = ${JSON.stringify(factoryArtifact.abi, null, 2)};

export const AUCTION_ABI = ${JSON.stringify(auctionArtifact.abi, null, 2)};
`;

  writeFileSync(abiPath, abiContent);
  console.log("✓ ABIs saved to:", abiPath);

  console.log("\n========================================");
  console.log("Deployment Summary:");
  console.log("========================================");
  console.log("Factory Address:", factoryAddress);
  console.log("Network:", "BSC Testnet");
  console.log("Chain ID:", 97);
  console.log("Block Explorer:", `https://testnet.bscscan.com/address/${factoryAddress}`);
  console.log("========================================\n");

  console.log("Next steps:");
  console.log("1. Verify contract on BSCScan (optional):");
  console.log(`   npx hardhat verify --network bscTestnet ${factoryAddress}`);
  console.log("2. Update .env file:");
  console.log(`   NEXT_PUBLIC_USE_LOCAL=false`);
  console.log(`   NEXT_PUBLIC_FACTORY_ADDRESS_TESTNET=${factoryAddress}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
