const { ethers, artifacts } = require("hardhat");
const { existsSync, mkdirSync, writeFileSync } = require("fs");
const { join } = require("path");

async function main() {
  console.log("Deploying contracts to local network...");

  // Get signers
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);

  // Get account balance
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "ETH");

  // Deploy AuctionFactory
  console.log("\nDeploying AuctionFactory...");
  const AuctionFactory = await ethers.getContractFactory("AuctionFactory");
  const factory = await AuctionFactory.deploy();
  await factory.waitForDeployment();

  const factoryAddress = await factory.getAddress();
  console.log("✓ AuctionFactory deployed to:", factoryAddress);

  // Create src directories if they don't exist
  const constantsDir = join(__dirname, "../src/constants");
  const utilsDir = join(__dirname, "../src/utils");

  if (!existsSync(constantsDir)) {
    mkdirSync(constantsDir, { recursive: true });
  }
  if (!existsSync(utilsDir)) {
    mkdirSync(utilsDir, { recursive: true });
  }

  // Save deployment config
  const config = {
    FACTORY_ADDRESS: factoryAddress,
    NETWORK: "localhost",
    CHAIN_ID: 31337
  };

  const configPath = join(constantsDir, "config.js");
  const configContent = `// Auto-generated by deployment script
// Do not edit manually

export const FACTORY_ADDRESS = "${config.FACTORY_ADDRESS}";

export const NETWORK_CONFIG = {
  chainId: "0x7a69", // 31337 in hex (Hardhat local)
  chainName: "Hardhat Local",
  nativeCurrency: {
    name: "ETH",
    symbol: "ETH",
    decimals: 18
  },
  rpcUrls: ["http://127.0.0.1:8545/"]
};
`;

  writeFileSync(configPath, configContent);
  console.log("✓ Config saved to:", configPath);

  // Save ABI files
  const factoryArtifact = await artifacts.readArtifact("AuctionFactory");
  const auctionArtifact = await artifacts.readArtifact("Auction");

  const abiPath = join(utilsDir, "abis.js");
  const abiContent = `// Auto-generated ABIs
// Do not edit manually

export const FACTORY_ABI = ${JSON.stringify(factoryArtifact.abi, null, 2)};

export const AUCTION_ABI = ${JSON.stringify(auctionArtifact.abi, null, 2)};
`;

  writeFileSync(abiPath, abiContent);
  console.log("✓ ABIs saved to:", abiPath);

  console.log("\n========================================");
  console.log("Deployment Summary:");
  console.log("========================================");
  console.log("Factory Address:", factoryAddress);
  console.log("Network:", "Hardhat Local (localhost:8545)");
  console.log("Chain ID:", 31337);
  console.log("========================================\n");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
